name: Test

on:
  push:
  schedule:
    - cron:  '0 12 1 * *'  # 12:00, first day of the month
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install test runner
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Build docs
        run: tox -e docs
      - name: Update docs
        if: |
          github.repository == 'krikarls/NORCRY' &&
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags')
        run: tox -e docs-deploy -- --force
